services:
  - type: web
    name: delhi-aqi-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT flask_app:app
    envVars:
      - key: AQI_API_KEY
        value: 4e84e711ecd384cb72016b0238185ae0a443dbe3
